"""Static interface for the native :mod:`pydmg._pydmg` extension."""


def inspect_json(path: str) -> str: ...
def inspect_filesystems_json(path: str) -> str: ...
def list_partitions_json(path: str) -> str: ...
def inspect_gpt_json(path: str, partition_index: int | None, strict: bool) -> str: ...
def read_partition(path: str, index: int) -> bytes: ...
def extract_partition(path: str, index: int, output_path: str) -> int: ...
def compute_data_checksum(path: str) -> int: ...
def verify_data_checksum(path: str) -> bool: ...
def list_fat32_entries_json(path: str, partition_index: int) -> str: ...
def extract_fat32_json(
    path: str,
    output_dir: str,
    partition_index: int = ...,
    overwrite: bool = ...,
) -> str: ...
def list_apple_entries_json(path: str, directory_path: str = ...) -> str: ...
def read_apple_file(path: str, file_path: str) -> bytes: ...
def extract_apple_file(path: str, file_path: str, output_path: str) -> int: ...
def create_dmg(
    source_dir: str,
    output_path: str,
    volume_label: str = ...,
    total_sectors: int = ...,
) -> None: ...
